version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - mv .next/static/**/* .next/standalone
      - mv .next/static/* .next/standalone

artifacts:
  files: "**/*"
  base-directory: ./next/standalone
