version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      # Create deployment package
      #- zip -r app-deployment-package.zip .next node_modules package.json package-lock.json server.js  # Add more files as needed

artifacts:
  files: "**\*"
